<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerG5vmq9t\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerG5vmq9t/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerG5vmq9t.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerG5vmq9t\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerG5vmq9t\appDevDebugProjectContainer(array(
    'container.build_hash' => 'G5vmq9t',
    'container.build_id' => '211238f3',
    'container.build_time' => 1532015312,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerG5vmq9t');
